import React, { useEffect } from "react";
import {
  Activity,
  AlertTriangle,
  CheckCircle2,
  Database,
  ExternalLink,
  FileCheck2,
  ShieldCheck,
} from "lucide-react";
import report from "../artifacts/uci_german_credit_run.json";

const C = {
  bg: "#11131D",
  panel: "#1B1F2E",
  panelLight: "#232838",
  brass: "#C99A53",
  teal: "#4FA8A0",
  text: "#EDEAE0",
  dim: "#8993AC",
  sage: "#6FA888",
  rust: "#C25B45",
  hairline: "#2D3245",
};

const MONO = "'IBM Plex Mono', monospace";
const SANS = "'IBM Plex Sans', sans-serif";

function useGoogleFonts() {
  useEffect(() => {
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href =
      "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600&display=swap";
    document.head.appendChild(link);
    return () => link.remove();
  }, []);
}

function percent(value, digits = 1) {
  return `${(value * 100).toFixed(digits)}%`;
}

function Card({ children, className = "" }) {
  return (
    <div
      className={`rounded-lg p-4 ${className}`}
      style={{ background: C.panel, border: `1px solid ${C.hairline}` }}
    >
      {children}
    </div>
  );
}

function Label({ children, color = C.dim }) {
  return (
    <div
      style={{
        fontFamily: MONO,
        color,
        fontSize: "0.62rem",
        letterSpacing: "0.08em",
      }}
    >
      {children}
    </div>
  );
}

function Metric({ label, value, detail, status }) {
  const color = status === "pass" ? C.sage : status === "fail" ? C.rust : C.text;
  return (
    <Card>
      <div className="flex items-start justify-between gap-3">
        <div>
          <div style={{ fontFamily: MONO, color, fontSize: "1.45rem", fontWeight: 700 }}>
            {value}
          </div>
          <div
            className="mt-1"
            style={{ fontFamily: MONO, color: C.text, fontSize: "0.68rem" }}
          >
            {label.toUpperCase()}
          </div>
        </div>
        {status === "pass" && <CheckCircle2 size={17} color={C.sage} />}
        {status === "fail" && <AlertTriangle size={17} color={C.rust} />}
      </div>
      <div className="mt-3" style={{ fontFamily: SANS, color: C.dim, fontSize: "0.72rem" }}>
        {detail}
      </div>
    </Card>
  );
}

function Stage({ number, name, status, detail }) {
  const passed = status === "PASS";
  const color = passed ? C.sage : status === "FAIL" ? C.rust : C.brass;
  return (
    <div className="rounded p-3" style={{ background: C.panelLight }}>
      <div className="flex items-start justify-between gap-3">
        <div>
          <Label>{String(number).padStart(2, "0")} · {name.toUpperCase()}</Label>
          <div className="mt-2" style={{ fontFamily: SANS, color: C.dim, fontSize: "0.72rem" }}>
            {detail}
          </div>
        </div>
        <span style={{ fontFamily: MONO, color, fontSize: "0.66rem", fontWeight: 700 }}>
          {status}
        </span>
      </div>
    </div>
  );
}

function ReferenceRun() {
  useGoogleFonts();
  const { baseline, dataset, methodology, pipeline, provenance, robustness, runtime } = report;
  const male = baseline.group_rates.male;
  const female = baseline.group_rates.female;
  const boundary = robustness.decision_boundary_sensitivity;
  const shift = robustness.distribution_shift;
  const ood = robustness.out_of_distribution;
  const mitigation = pipeline.mitigation;
  const genderPassed = baseline.diagnostic_thresholds_passed.disparate_impact_gte_0_80
    && baseline.diagnostic_thresholds_passed.statistical_parity_gap_lte_0_10;

  return (
    <div
      className="h-full overflow-y-auto px-5 py-6 sm:px-8"
      style={{
        background: `radial-gradient(ellipse at top, ${C.panel} 0%, ${C.bg} 65%)`,
        color: C.text,
      }}
    >
      <div className="mx-auto max-w-6xl">
        <div className="mb-6 flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <Database size={17} color={C.teal} />
              <Label color={C.teal}>REAL DATA · REPRODUCIBLE REFERENCE RUN</Label>
            </div>
            <h1 style={{ fontFamily: MONO, fontSize: "1.35rem", fontWeight: 700 }}>
              UCI German Credit — Six-Stage Fairness Audit
            </h1>
            <p
              className="mt-2 max-w-2xl"
              style={{ fontFamily: SANS, color: C.dim, fontSize: "0.84rem", lineHeight: 1.55 }}
            >
              This view is separate from the synthetic product scenario. Every value below comes
              from the repository JSON artifact generated by the local Python reference audit.
            </p>
          </div>
          <a
            href={provenance.source}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded px-3 py-2"
            style={{ border: `1px solid ${C.teal}`, color: C.teal, fontFamily: MONO, fontSize: "0.66rem" }}
          >
            OFFICIAL UCI SOURCE <ExternalLink size={13} />
          </a>
        </div>

        <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <Metric label="Records" value={dataset.rows.toLocaleString()} detail="Official dataset rows" />
          <Metric label="Features" value={dataset.encoded_features} detail="Encoded model inputs" />
          <Metric label="Test accuracy" value={percent(baseline.accuracy)} detail={`${dataset.test_rows} held-out rows`} />
          <Metric
            label="Mitigation"
            value={mitigation.mitigation_passed ? "PASS" : "INCOMPLETE"}
            detail={`${mitigation.sensitive_attribute} · ${mitigation.constraint}`}
            status={mitigation.mitigation_passed ? "pass" : "fail"}
          />
        </div>

        <Card className="mb-6">
          <div className="mb-4 flex items-center justify-between">
            <Label color={C.teal}>EXECUTED PIPELINE · REAL ARTIFACT</Label>
            <Activity size={17} color={C.teal} />
          </div>
          <div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">
            <Stage number={1} name="Ingestion" status="PASS" detail={`${dataset.rows} rows validated; compound field decomposed`} />
            <Stage number={2} name="XGBoost baseline" status="PASS" detail={`${percent(baseline.accuracy)} test accuracy`} />
            <Stage
              number={3}
              name="Disparate impact"
              status={pipeline.disparate_impact.any_violation ? "FAIL" : "PASS"}
              detail={`${pipeline.disparate_impact.n_pass} pass · ${pipeline.disparate_impact.n_fail} fail`}
            />
            <Stage
              number={4}
              name="Equalized odds"
              status={pipeline.equalized_odds.any_violation ? "FAIL" : "PASS"}
              detail={`${pipeline.equalized_odds.n_pass} pass · ${pipeline.equalized_odds.n_fail} fail`}
            />
            <Stage
              number={5}
              name="Intersectional bias"
              status={pipeline.intersectional_bias.any_violation ? "FAIL" : "PASS"}
              detail={`${pipeline.intersectional_bias.n_pass} pass · ${pipeline.intersectional_bias.n_insufficient} insufficient`}
            />
            <Stage
              number={6}
              name="Fairlearn mitigation"
              status={mitigation.mitigation_passed ? "PASS" : "FAIL"}
              detail={`${mitigation.sensitive_attribute}: DPR ${mitigation.fairness.before.demographic_parity_ratio.toFixed(4)} → ${mitigation.fairness.after.demographic_parity_ratio.toFixed(4)}; accuracy cost ${percent(mitigation.performance.accuracy_cost)}`}
            />
          </div>
        </Card>

        <div className="mb-6 grid grid-cols-1 gap-4 lg:grid-cols-2">
          <Card>
            <div className="mb-4 flex items-center justify-between">
              <Label>GENDER FAIRNESS · PREDICTED APPROVALS</Label>
              <ShieldCheck size={17} color={genderPassed ? C.sage : C.rust} />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="rounded p-3" style={{ background: C.panelLight }}>
                <div style={{ fontFamily: MONO, color: C.text, fontSize: "1.2rem", fontWeight: 700 }}>
                  {percent(male.predicted_approval_rate)}
                </div>
                <div className="mt-1" style={{ fontFamily: MONO, color: C.dim, fontSize: "0.62rem" }}>
                  MALE · n={male.n}
                </div>
              </div>
              <div className="rounded p-3" style={{ background: C.panelLight }}>
                <div style={{ fontFamily: MONO, color: C.text, fontSize: "1.2rem", fontWeight: 700 }}>
                  {percent(female.predicted_approval_rate)}
                </div>
                <div className="mt-1" style={{ fontFamily: MONO, color: C.dim, fontSize: "0.62rem" }}>
                  FEMALE · n={female.n}
                </div>
              </div>
            </div>
            <div className="mt-4 space-y-2">
              <div className="flex items-center justify-between border-t pt-3" style={{ borderColor: C.hairline }}>
                <span style={{ fontFamily: SANS, color: C.dim, fontSize: "0.78rem" }}>Disparate impact</span>
                <span style={{ fontFamily: MONO, color: genderPassed ? C.sage : C.rust, fontWeight: 700 }}>{baseline.disparate_impact.toFixed(4)} · {genderPassed ? "PASS" : "FAIL"}</span>
              </div>
              <div className="flex items-center justify-between border-t pt-3" style={{ borderColor: C.hairline }}>
                <span style={{ fontFamily: SANS, color: C.dim, fontSize: "0.78rem" }}>Statistical parity gap</span>
                <span style={{ fontFamily: MONO, color: genderPassed ? C.sage : C.rust, fontWeight: 700 }}>{baseline.statistical_parity_gap.toFixed(4)} · {genderPassed ? "PASS" : "FAIL"}</span>
              </div>
            </div>
          </Card>

          <Card>
            <div className="mb-4 flex items-center justify-between">
              <Label>ARTICLE 15 · EXECUTABLE ROBUSTNESS</Label>
              <Activity size={17} color={C.rust} />
            </div>
            <div className="space-y-3">
              <div className="flex items-start justify-between gap-4 border-t pt-3" style={{ borderColor: C.hairline }}>
                <div>
                  <div style={{ fontFamily: SANS, fontSize: "0.8rem" }}>Distribution shift</div>
                  <div className="mt-1" style={{ fontFamily: MONO, color: C.dim, fontSize: "0.64rem" }}>
                    accuracy {shift.baseline_accuracy.toFixed(4)} → {shift.shifted_accuracy.toFixed(4)}
                  </div>
                </div>
                <span style={{ fontFamily: MONO, color: C.sage, fontSize: "0.68rem" }}>PASS</span>
              </div>
              <div className="flex items-start justify-between gap-4 border-t pt-3" style={{ borderColor: C.hairline }}>
                <div>
                  <div style={{ fontFamily: SANS, fontSize: "0.8rem" }}>Boundary sensitivity</div>
                  <div className="mt-1" style={{ fontFamily: MONO, color: C.dim, fontSize: "0.64rem" }}>
                    {boundary.n_borderline} borderline cases · threshold {percent(boundary.flip_threshold, 0)}
                  </div>
                </div>
                <span style={{ fontFamily: MONO, color: C.rust, fontSize: "0.68rem" }}>
                  {percent(boundary.flip_rate, 0)} · FAIL
                </span>
              </div>
              <div className="flex items-start justify-between gap-4 border-t pt-3" style={{ borderColor: C.hairline }}>
                <div>
                  <div style={{ fontFamily: SANS, fontSize: "0.8rem" }}>Malformed input handling</div>
                  <div className="mt-1" style={{ fontFamily: MONO, color: C.dim, fontSize: "0.64rem" }}>
                    {robustness.malformed_input_handling.length} explicit cases
                  </div>
                </div>
                <span style={{ fontFamily: MONO, color: C.sage, fontSize: "0.68rem" }}>4/4 PASS</span>
              </div>
              <div className="flex items-start justify-between gap-4 border-t pt-3" style={{ borderColor: C.hairline }}>
                <div>
                  <div style={{ fontFamily: SANS, fontSize: "0.8rem" }}>Out-of-distribution</div>
                  <div className="mt-1" style={{ fontFamily: MONO, color: C.dim, fontSize: "0.64rem" }}>
                    {ood.n_flagged}/{ood.n_queried} rows beyond z={ood.z_threshold.toFixed(1)}
                  </div>
                </div>
                <span style={{ fontFamily: MONO, color: C.brass, fontSize: "0.68rem" }}>
                  {percent(ood.flagged_rate)} · INFO
                </span>
              </div>
            </div>
          </Card>
        </div>

        <Card className="mb-6">
          <div className="mb-4 flex items-center gap-2">
            <FileCheck2 size={16} color={C.brass} />
            <Label color={C.brass}>PROVENANCE & LIMITATIONS</Label>
          </div>
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            <div className="space-y-2" style={{ fontFamily: MONO, color: C.dim, fontSize: "0.68rem" }}>
              <div>Dataset: {provenance.dataset}</div>
              <div>DOI: {provenance.doi}</div>
              <div>License: {provenance.license}</div>
              <div>Split: {methodology.train_test_split}</div>
              <div>Runtime: Python {runtime.python} · pandas {runtime.pandas} · XGBoost {runtime.xgboost}</div>
            </div>
            <ul className="space-y-2">
              {methodology.limitations.map((limitation) => (
                <li key={limitation} className="flex gap-2" style={{ fontFamily: SANS, color: C.dim, fontSize: "0.76rem" }}>
                  <span style={{ color: C.brass }}>·</span>
                  <span>{limitation}</span>
                </li>
              ))}
            </ul>
          </div>
        </Card>
      </div>
    </div>
  );
}

export default ReferenceRun;
